package models

import (
	"context"
	"errors"
	"fmt"
	"github.com/av-huette/avh-booking-system/internal/database"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"strconv"
)

// Account represents a user account in the booking system.
// It contains personal information, financial details, and account status.
// The monetary fields (Balance and MaxDebt) represent the smallest currency unit (e.g., cents)
type Account struct {
	Id        int              `json:"id" db:"account_id"`
	FirstName string           `json:"firstName" db:"first_name"`
	Nickname  string           `json:"nickname" db:"nickname"`
	LastName  string           `json:"lastName" db:"last_name"`
	Email     string           `json:"email" db:"email"`
	Phone     string           `json:"phone" db:"phone"`
	Balance   int              `json:"balance" db:"balance"`
	MaxDebt   int              `json:"maxDebt" db:"max_debt"`
	Category  int              `json:"category" db:"category"`
	Enabled   bool             `json:"enabled" db:"enabled"`
	CreatedAt pgtype.Timestamp `json:"createdAt" db:"created_at"`
}

// CreateAccount creates a new Account with the provided details.
// Id, Enabled (true) and CreatedAt are not set as they are auto-generated by the database.
func CreateAccount(firstName string, nickName string, lastName string,
	email string, phone string, balance int, maxDebt int, category int) Account {
	return Account{
		FirstName: firstName,
		Nickname:  nickName,
		LastName:  lastName,
		Email:     email,
		Phone:     phone,
		Balance:   balance,
		MaxDebt:   maxDebt,
		Category:  category,
		//Enabled:   true, // set by the database
	}
}

// AccountModel provides database operations for Account entities.
type AccountModel struct {
	DB *database.DB
}

// Get retrieves accounts based on the provided query specification.
// It executes the SQL statement generated by the query and returns all matching accounts.
// Returns an error if the query execution fails or if row collection encounters an issue.
func (m *AccountModel) Get(query *Query) ([]Account, error) {
	ctx := context.Background()
	stmt := query.SqlStatement()
	rows, err := m.DB.Query(ctx, stmt)

	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) {
			fmt.Println(pgErr.Message)
			fmt.Println(pgErr.Code)
		}
	}

	accounts, err := pgx.CollectRows(rows, pgx.RowToStructByName[Account])
	if err != nil {
		fmt.Printf("CollectRows error: %v", err)
		return nil, err
	}

	return accounts, nil
}

// GetById retrieves a single account by its ID.
// Returns a pointer to the Account if found, nil if not found.
// Returns DbQueryError if the query returns no results or multiple results.
func (m *AccountModel) GetById(id int) (*Account, error) {
	filters := []Filter{{Column: "account_id", Operator: Eq, Value: strconv.Itoa(id)}}
	query := Query{Table: TableAccount, Filter: filters}

	accounts, err := m.Get(&query)
	if err != nil {
		return nil, err
	}
	if len(accounts) == 1 {
		return &accounts[0], nil
	}

	return nil, DbQueryError
}

// Insert adds a new account to the database.
// The Id, Enabled and CreatedAt fields are ignored as they are auto-generated by the database.
// Returns the newly created account's ID and any error encountered.
func (m *AccountModel) Insert(account Account) (int, error) {
	ctx := context.Background()
	query := `
        INSERT INTO account (first_name, nickname, last_name, email, phone, balance, max_debt, category) 
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
        RETURNING account_id`
	var id int
	err := m.DB.QueryRow(ctx, query, account.FirstName,
		account.Nickname,
		account.LastName,
		account.Email,
		account.Phone,
		account.Balance,
		account.MaxDebt,
		account.Category).Scan(&id)

	return id, err
}

// Update modifies an existing account in the database.
// Note: This method does NOT update the Balance field. Balance modifications
// should be handled through separate transaction/payment operations.
// Returns the updated account's ID and any error encountered.
func (m *AccountModel) Update(account Account) (int, error) {
	ctx := context.Background()
	query := `
        UPDATE account 
        SET first_name = $1, nickname = $2, last_name = $3, email = $4, phone = $5, max_debt = $6, category = $7, enabled = $8
        WHERE account_id = $9
        RETURNING account_id`
	var id int
	err := m.DB.QueryRow(ctx, query,
		account.FirstName,
		account.Nickname,
		account.LastName,
		account.Email,
		account.Phone,
		account.MaxDebt,
		account.Category,
		account.Enabled,
		account.Id).Scan(&id)

	return id, err
}

// Note: we do NOT support deletion of accounts
