package models

import "github.com/jackc/pgx/v5/pgtype"

// Account represents a user account in the booking system.
// It contains personal information, financial details, and account status.
// The monetary fields (Balance and MaxDebt) represent the smallest currency unit (e.g., cents)
type Account struct {
	ID        int              `json:"id" db:"account_id"`
	FirstName string           `json:"firstName" db:"first_name"`
	Nickname  string           `json:"nickname" db:"nickname"`
	LastName  string           `json:"lastName" db:"last_name"`
	Email     string           `json:"email" db:"email"`
	Phone     string           `json:"phone" db:"phone"`
	Balance   int              `json:"balance" db:"balance"`
	MaxDebt   int              `json:"maxDebt" db:"max_debt"`
	Category  int              `json:"category" db:"category"`
	Enabled   bool             `json:"enabled" db:"enabled"`
	CreatedAt pgtype.Timestamp `json:"createdAt" db:"created_at"`
}

// CreateAccount creates a new Account with the provided details.
// ID, Enabled (true) and CreatedAt are not set as they are auto-generated by the database.
func CreateAccount(firstName string, nickName string, lastName string,
	email string, phone string, balance int, maxDebt int, category int) Account {
	return Account{
		FirstName: firstName,
		Nickname:  nickName,
		LastName:  lastName,
		Email:     email,
		Phone:     phone,
		Balance:   balance,
		MaxDebt:   maxDebt,
		Category:  category,
		//Enabled:   true, // set by the database
	}
}
