package models

import (
	"context"
	"database/sql"
	"errors"
	"github.com/av-huette/avh-booking-system/internal/database"
)

// Category represents a classification type in the booking system.
// Categories can be used to group accounts and products.
type Category struct {
	Id      int    `json:"id" db:"category_id"`
	Name    string `json:"name" db:"name"`
	Enabled bool   `json:"enabled" db:"enabled"`
	Icon    string `json:"icon" db:"icon"`
	Type    string `json:"type" db:"type"`
}

// CategoryModel provides database operations for Category entities.
type CategoryModel struct {
	DB *database.DB
}

// CreateCategory creates a new Category with the provided details.
// Id and Enabled (true) are not set as they are auto-generated by the database.
func CreateCategory(name string, icon string, type_ string) Category {
	return Category{
		Name: name,
		Icon: icon,
		Type: type_,
	}
}

// Insert adds a new category to the database.
// Returns the newly created category's ID and any error encountered.
func (m *CategoryModel) Insert(category Category) (int, error) {
	ctx := context.Background()
	query := `
        INSERT INTO category (name, enabled, icon, type) 
        VALUES ($1, $2, $3, $4)
        RETURNING category_id`
	var id int
	err := m.DB.QueryRow(ctx, query,
		category.Name,
		category.Enabled,
		category.Icon,
		category.Type,
	).Scan(&id)

	return id, err
}

// GetById retrieves a category by its ID.
// Returns a pointer to the Category if found, nil otherwise.
// Returns database.ErrNoRecord if no category with the given ID exists.
func (m *CategoryModel) GetById(id int) (*Category, error) {
	ctx := context.Background()
	stmt := `SELECT category_id, name, enabled, icon, type
			FROM category
			WHERE category_id = $1`
	row := m.DB.QueryRow(ctx, stmt, id)

	var cat Category
	err := row.Scan(&cat.Id, &cat.Name, &cat.Enabled, &cat.Icon, &cat.Type)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, database.ErrNoRecord
		} else {
			return nil, err
		}
	}

	return &cat, nil
}
