package models

// Category represents a classification type in the booking system.
// Categories can be used to group accounts and products.
type Category struct {
	ID      int    `json:"id" db:"category_id"`
	Name    string `json:"name" db:"name"`
	Enabled bool   `json:"enabled" db:"enabled"`
	Icon    string `json:"icon" db:"icon"`
	Type    string `json:"type" db:"type"`
}

// CreateCategory creates a new Category with the provided details.
// ID and Enabled (true) are not set as they are auto-generated by the database.
func CreateCategory(name string, icon string, categoryType string) Category {
	return Category{
		Name: name,
		Icon: icon,
		Type: categoryType,
	}
}
