package models

import (
	"context"
	"database/sql"
	"errors"
	"github.com/av-huette/avh-booking-system/internal/database"
)

// Location represents a physical location of a booking system client.
type Location struct {
	Id   int    `json:"id" db:"location_id"`
	Name string `json:"name" db:"name"`
}

// LocationModel provides database operations for Location entities.
type LocationModel struct {
	DB *database.DB
}

// CreateLocation creates a new Location with the provided name.
// The Id is auto-generated by the database on insert.
func CreateLocation(name string) Location {
	return Location{
		Name: name,
	}
}

// Insert adds a new location to the database.
// Returns the newly created location's ID and any error encountered.
func (m *LocationModel) Insert(location Location) (int, error) {
	ctx := context.Background()
	query := `
        INSERT INTO location (name) 
        VALUES ($1)
        RETURNING location_id;`
	var id int
	err := m.DB.QueryRow(ctx, query, location.Name).Scan(&id)

	return id, err
}

// GetById retrieves a location by its ID.
// Returns a pointer to the Location if found, nil otherwise.
// Returns database.ErrNoRecord if no location with the given ID exists.
func (m *LocationModel) GetById(id int) (*Location, error) {
	ctx := context.Background()
	stmt := `SELECT location_id, name
			FROM location
			WHERE location_id = $1`
	row := m.DB.QueryRow(ctx, stmt, id)

	var location Location
	err := row.Scan(&location.Id, &location.Name)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, database.ErrNoRecord
		} else {
			return nil, err
		}
	}

	return &location, nil
}
