package models

// Location represents a physical location of a booking system client.
type Location struct {
	ID   int    `json:"id" db:"location_id"`
	Name string `json:"name" db:"name"`
}

// CreateLocation creates a new Location with the provided name.
// The ID is auto-generated by the database on insert.
func CreateLocation(name string) Location {
	return Location{
		Name: name,
	}
}
