package models

import "github.com/jackc/pgx/v5/pgtype"

// Order represents a purchase order placed by an account.
type Order struct {
	ID        int              `json:"id" db:"order_id"`
	AccountID int              `json:"accountId" db:"account"`
	CreatedAt pgtype.Timestamp `json:"createdAt" db:"created_at"`
}

// CreateOrder creates a new Order for the given account.
// ID and CreatedAt are auto-generated by the database.
func CreateOrder(accountID int) Order {
	return Order{AccountID: accountID}
}
