package models

// ProductGroup represents a hierarchical grouping of products.
// Product groups can have parent groups, allowing for nested categorization.
// A nil ParentID indicates a top-level group with no parent.
type ProductGroup struct {
	ID       int    `json:"id" db:"product_group_id"`
	Name     string `json:"name" db:"name"`
	ParentID *int   `json:"parent_id" db:"parent"`
}

// CreateProductGroup creates a new ProductGroup with the provided details.
// The ID is auto-generated by the database on insert.
func CreateProductGroup(name string, parentID *int) ProductGroup {
	return ProductGroup{
		Name:     name,
		ParentID: parentID,
	}
}
