package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/av-huette/avh-booking-system/internal/database"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

// Product represents a purchasable item or service in the booking system.
// Products have pricing, tax information, grouping, and measurement details.
type Product struct {
	Id             int              `json:"id" db:"product_id"`
	Name           string           `json:"name" db:"name"`
	Price          int              `json:"price" db:"price"`
	VatId          int              `json:"vat" db:"vat"`
	ProductGroupId int              `json:"productGroup" db:"product_group"`
	Size           int              `json:"size" db:"size"`
	UnitId         int              `json:"unit" db:"unit"`
	CategoryId     int              `json:"category" db:"category"`
	CreatedAt      pgtype.Timestamp `json:"createdAt" db:"created_at"`
}

// ProductModel provides database operations for Product entities.
type ProductModel struct {
	DB *database.DB
}

// CreateProduct creates a new Product with the provided details.
// The Id and CreatedAt fields are auto-generated by the database on insert.
func CreateProduct(name string, price int, vatId int, prodGroupId int, size int,
	unitId int, catId int) Product {
	return Product{
		Name:           name,
		Price:          price,
		VatId:          vatId,
		ProductGroupId: prodGroupId,
		Size:           size,
		UnitId:         unitId,
		CategoryId:     catId,
	}
}

// Get retrieves products based on the provided query specification.
// It executes the SQL statement generated by the query and returns all matching products.
// Returns an error if the query execution fails or if row collection encounters an issue.
func (m *ProductModel) Get(query *Query) ([]Product, error) {
	ctx := context.Background()
	stmt := buildSelectSQL(query)
	rows, err := m.DB.Query(ctx, stmt)

	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) {
			fmt.Println(pgErr.Message)
			fmt.Println(pgErr.Code)
		}
	}

	products, err := pgx.CollectRows(rows, pgx.RowToStructByName[Product])
	if err != nil {
		fmt.Printf("CollectRows error: %v", err)
		return nil, err
	}

	return products, nil
}

// GetById retrieves a product by its ID.
// Returns a pointer to the Product if found, nil otherwise.
// Returns database.ErrNoRecord if no product with the given ID exists.
func (m *ProductModel) GetById(productId int) (*Product, error) {
	ctx := context.Background()
	stmt := `SELECT product_id, name, price, vat, product_group, size, unit, category, created_at
			FROM product
			WHERE product_id = $1`
	row := m.DB.QueryRow(ctx, stmt, productId)

	var product Product
	err := row.Scan(&product.Id, &product.Name, &product.Price, &product.VatId, &product.ProductGroupId,
		&product.Size, &product.UnitId, &product.CategoryId, &product.CreatedAt)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, database.ErrNoRecord
		} else {
			return nil, err
		}
	}

	return &product, nil
}

// Insert adds a new product to the database.
// Returns the newly created product's ID and any error encountered.
func (m *ProductModel) Insert(product Product) (int, error) {
	ctx := context.Background()
	query := `
        INSERT INTO product (name, price, vat, product_group, size, unit, category) 
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        RETURNING product_id`
	var id int
	err := m.DB.QueryRow(ctx, query,
		product.Name,
		product.Price,
		product.VatId,
		product.ProductGroupId,
		product.Size,
		product.UnitId,
		product.CategoryId,
	).Scan(&id)

	return id, err
}
