package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/av-huette/avh-booking-system/internal/database"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// ProductVisibility represents a rule that controls which products are visible
// to which categories at which locations.
type ProductVisibility struct {
	Id         int `json:"id" db:"product_visibility_id"`
	CategoryId int `json:"categoryId" db:"category"`
	LocationId int `json:"locationId" db:"location"`
	ProductId  int `json:"productId" db:"product"`
}

// ProductVisibilityModel provides database operations for ProductVisibility entities.
type ProductVisibilityModel struct {
	DB *database.DB
}

// CreateProductVisibility creates a new ProductVisibility rule with the provided details.
// The Id is auto-generated by the database on insert.
func CreateProductVisibility(category int, location int, product int) ProductVisibility {
	return ProductVisibility{
		CategoryId: category,
		LocationId: location,
		ProductId:  product,
	}
}

// Get retrieves ProductVisibilities based on the provided query specification.
// It executes the SQL statement generated by the query and returns all matching ProductVisibilities.
// Returns an error if the query execution fails or if row collection encounters an issue.
func (m *ProductVisibilityModel) Get(query *Query) ([]ProductVisibility, error) {
	ctx := context.Background()
	stmt := buildSelectSQL(query)
	rows, err := m.DB.Query(ctx, stmt)

	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) {
			fmt.Println(pgErr.Message)
			fmt.Println(pgErr.Code)
		}
	}

	visibilities, err := pgx.CollectRows(rows, pgx.RowToStructByName[ProductVisibility])
	if err != nil {
		fmt.Printf("CollectRows error: %v", err)
		return nil, err
	}

	return visibilities, nil
}

// GetById retrieves a product visibility rule by its ID.
// Returns a pointer to the ProductVisibility if found, nil otherwise.
// Returns database.ErrNoRecord if no rule with the given ID exists.
func (m *ProductVisibilityModel) GetById(id int) (*ProductVisibility, error) {
	ctx := context.Background()
	stmt := `SELECT product_visibility_id, category, location, product
			FROM product_visibility
			WHERE product_visibility_id = $1`
	row := m.DB.QueryRow(ctx, stmt, id)

	var productVisibility ProductVisibility
	err := row.Scan(&productVisibility.Id, &productVisibility.CategoryId, &productVisibility.LocationId, &productVisibility.ProductId)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, database.ErrNoRecord
		} else {
			return nil, err
		}
	}

	return &productVisibility, nil
}

// Insert adds a new product visibility rule to the database.
// Returns the newly created rule's ID and any error encountered.
func (m *ProductVisibilityModel) Insert(visibility ProductVisibility) (int, error) {
	ctx := context.Background()
	var id int
	query := `
        INSERT INTO product_visibility (category, location, product) 
        VALUES ($1, $2, $3)
        RETURNING product_visibility_id`
	err := m.DB.QueryRow(ctx, query, visibility.CategoryId, visibility.LocationId, visibility.ProductId).Scan(&id)

	return id, err
}

// Delete an existing visibility in the database.
func (m *ProductVisibilityModel) Delete(id int) (int, error) {
	ctx := context.Background()
	query := `
        DELETE FROM product_visibility 
        WHERE product_visibility_id = $1
				RETURNING $1;
				`
	err := m.DB.QueryRow(ctx, query, id).Scan(&id)

	return id, err
}
