package models

// ProductVisibility represents a rule that controls which products are visible
// to which categories at which locations.
type ProductVisibility struct {
	Id         int `json:"id" db:"product_visibility_id"`
	CategoryId int `json:"categoryId" db:"category"`
	LocationId int `json:"locationId" db:"location"`
	ProductId  int `json:"productId" db:"product"`
}

// CreateProductVisibility creates a new ProductVisibility rule with the provided details.
// The Id is auto-generated by the database on insert.
func CreateProductVisibility(category int, location int, product int) ProductVisibility {
	return ProductVisibility{
		CategoryId: category,
		LocationId: location,
		ProductId:  product,
	}
}
