package models

// ProductVisibility represents a rule that controls which products are visible
// to which categories at which locations.
type ProductVisibility struct {
	ID         int `json:"id" db:"product_visibility_id"`
	CategoryID int `json:"categoryId" db:"category"`
	LocationID int `json:"locationId" db:"location"`
	ProductID  int `json:"productId" db:"product"`
}

// CreateProductVisibility creates a new ProductVisibility rule with the provided details.
// The ID is auto-generated by the database on insert.
func CreateProductVisibility(category int, location int, product int) ProductVisibility {
	return ProductVisibility{
		CategoryID: category,
		LocationID: location,
		ProductID:  product,
	}
}
