package models

import "github.com/jackc/pgx/v5/pgtype"

// Product represents a purchasable item or service in the booking system.
// Products have pricing, tax information, grouping, and measurement details.
type Product struct {
	Id             int              `json:"id" db:"product_id"`
	Name           string           `json:"name" db:"name"`
	Price          int              `json:"price" db:"price"`
	VatId          int              `json:"vat" db:"vat"`
	ProductGroupId int              `json:"productGroup" db:"product_group"`
	Size           int              `json:"size" db:"size"`
	UnitId         int              `json:"unit" db:"unit"`
	CategoryId     int              `json:"category" db:"category"`
	CreatedAt      pgtype.Timestamp `json:"createdAt" db:"created_at"`
}

// CreateProduct creates a new Product with the provided details.
// The Id and CreatedAt fields are auto-generated by the database on insert.
func CreateProduct(name string, price int, vatId int, prodGroupId int, size int,
	unitId int, catId int) Product {
	return Product{
		Name:           name,
		Price:          price,
		VatId:          vatId,
		ProductGroupId: prodGroupId,
		Size:           size,
		UnitId:         unitId,
		CategoryId:     catId,
	}
}
