package models

import (
	"context"
	"database/sql"
	"errors"
	"github.com/av-huette/avh-booking-system/internal/database"
)

// ProductGroup represents a hierarchical grouping of products.
// Product groups can have parent groups, allowing for nested categorization.
// A ParentId of 0 or less indicates a top-level group with no parent.
type ProductGroup struct {
	Id       int    `json:"id" db:"product_group_id"`
	Name     string `json:"name" db:"name"`
	ParentId int    `json:"parent_id" db:"parent"`
}

// ProductGroupModel provides database operations for ProductGroup entities.
type ProductGroupModel struct {
	DB *database.DB
}

// CreateProductGroup creates a new ProductGroup with the provided details.
// The Id is auto-generated by the database on insert.
func CreateProductGroup(name string, parentId int) ProductGroup {
	return ProductGroup{
		Name:     name,
		ParentId: parentId,
	}
}

// Insert adds a new product group to the database.
// Returns the newly created product group's ID and any error encountered.
func (m *ProductGroupModel) Insert(group ProductGroup) (int, error) {
	ctx := context.Background()
	var id int
	var err error
	if group.ParentId <= 0 {
		query := `
        INSERT INTO product_group (name) 
        VALUES ($1)
        RETURNING product_group_id`
		err = m.DB.QueryRow(ctx, query, group.Name).Scan(&id)
	} else {
		query := `
        INSERT INTO product_group (name, parent) 
        VALUES ($1, $2)
        RETURNING product_group_id`
		err = m.DB.QueryRow(ctx, query, group.Name, group.ParentId).Scan(&id)
	}

	return id, err
}

// GetById retrieves a product group by its ID.
// Returns a pointer to the ProductGroup if found, nil otherwise.
// Returns database.ErrNoRecord if no product group with the given ID exists.
func (m *ProductGroupModel) GetById(id int) (*ProductGroup, error) {
	ctx := context.Background()
	stmt := `SELECT product_group_id, name, parent
			FROM product_group
			WHERE product_group_id = $1`
	row := m.DB.QueryRow(ctx, stmt, id)

	var productGroup ProductGroup
	var parentId *int // pointer to read null
	err := row.Scan(&productGroup.Id, &productGroup.Name, &parentId)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, database.ErrNoRecord
		} else {
			return nil, err
		}
	}
	if parentId == nil {
		productGroup.ParentId = 0
	} else {
		productGroup.ParentId = *parentId
	}

	return &productGroup, nil
}
