package models

// ProductGroup represents a hierarchical grouping of products.
// Product groups can have parent groups, allowing for nested categorization.
// A ParentId of 0 or less indicates a top-level group with no parent.
type ProductGroup struct {
	Id       int    `json:"id" db:"product_group_id"`
	Name     string `json:"name" db:"name"`
	ParentId int    `json:"parent_id" db:"parent"`
}

// CreateProductGroup creates a new ProductGroup with the provided details.
// The Id is auto-generated by the database on insert.
func CreateProductGroup(name string, parentId int) ProductGroup {
	return ProductGroup{
		Name:     name,
		ParentId: parentId,
	}
}
