package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"github.com/av-huette/avh-booking-system/internal/database"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Unit represents a unit of measurement used for products in the booking system.
// Examples include pieces, liters, kilograms, hours, etc.
type Unit struct {
	Id   int    `json:"id" db:"unit_id"`
	Name string `json:"name" db:"name"`
}

// UnitModel provides database operations for Unit entities.
type UnitModel struct {
	DB *database.DB
}

// CreateUnit creates a new Unit with the provided name.
// The Id is auto-generated by the database on insert.
func CreateUnit(name string) Unit {
	return Unit{
		Name: name,
	}
}

// Get retrieves units based on the provided query specification.
// It executes the SQL statement generated by the query and returns all matching units.
// Returns an error if the query execution fails or if row collection encounters an issue.
func (m *UnitModel) Get(query *Query) ([]Unit, error) {
	ctx := context.Background()
	stmt := buildSelectSQL(query)
	rows, err := m.DB.Query(ctx, stmt)

	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) {
			fmt.Println(pgErr.Message)
			fmt.Println(pgErr.Code)
		}
	}

	units, err := pgx.CollectRows(rows, pgx.RowToStructByName[Unit])
	if err != nil {
		fmt.Printf("CollectRows error: %v", err)
		return nil, err
	}

	return units, nil
}

// GetById retrieves a unit by its ID.
// Returns a pointer to the Unit if found, nil otherwise.
// Returns database.ErrNoRecord if no unit with the given ID exists.
func (m *UnitModel) GetById(id int) (*Unit, error) {
	ctx := context.Background()
	stmt := `SELECT unit_id, name
			FROM unit
			WHERE unit_id = $1`
	row := m.DB.QueryRow(ctx, stmt, id)

	var unit Unit
	err := row.Scan(&unit.Id, &unit.Name)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, database.ErrNoRecord
		} else {
			return nil, err
		}
	}

	return &unit, nil
}

// Insert adds a new unit to the database.
// Returns the newly created unit's ID and any error encountered.
func (m *UnitModel) Insert(unit Unit) (int, error) {
	ctx := context.Background()
	query := `
        INSERT INTO unit (name) 
        VALUES ($1)
        RETURNING unit_id;`
	var id int
	err := m.DB.QueryRow(ctx, query, unit.Name).Scan(&id)

	return id, err
}
