package models

// Unit represents a unit of measurement used for products in the booking system.
// Examples include pieces, liters, kilograms, hours, etc.
type Unit struct {
	ID   int    `json:"id" db:"unit_id"`
	Name string `json:"name" db:"name"`
}

// CreateUnit creates a new Unit with the provided name.
// The ID is auto-generated by the database on insert.
func CreateUnit(name string) Unit {
	return Unit{
		Name: name,
	}
}
