package models

// Vat represents a Value Added Tax (VAT) or sales tax rate in the booking system.
// VAT rates are applied to products to calculate the tax component of prices.
// The rate is represented as a percentage (e.g., 19 = 19%)
type Vat struct {
	ID   int `json:"id" db:"vat_id"`
	Rate int `json:"rate" db:"rate"`
}

// CreateVat creates a new Vat with the provided rate.
// The ID is auto-generated by the database on insert.
func CreateVat(rate int) Vat {
	return Vat{
		Rate: rate,
	}
}
