package models

import (
	"context"
	"database/sql"
	"errors"
	"github.com/av-huette/avh-booking-system/internal/database"
)

// Vat represents a Value Added Tax (VAT) or sales tax rate in the booking system.
// VAT rates are applied to products to calculate the tax component of prices.
// The rate is represented as a percentage (e.g., 19 = 19%)
type Vat struct {
	Id   int `json:"id" db:"vat_id"`
	Rate int `json:"rate" db:"rate"`
}

// VatModel provides database operations for Vat entities.
type VatModel struct {
	DB *database.DB
}

// CreateVat creates a new Vat with the provided rate.
// The Id is auto-generated by the database on insert.
func CreateVat(rate int) Vat {
	return Vat{
		Rate: rate,
	}
}

// Insert adds a new VAT rate to the database.
// Returns the newly created VAT rate's ID and any error encountered.
func (m *VatModel) Insert(vat Vat) (int, error) {
	ctx := context.Background()
	query := `
        INSERT INTO vat (rate) 
        VALUES ($1)
        RETURNING vat_id;`
	var id int
	err := m.DB.QueryRow(ctx, query, vat.Rate).Scan(&id)

	return id, err
}

// GetById retrieves a VAT rate by its ID.
// Returns a pointer to the Vat if found, nil otherwise.
// Returns database.ErrNoRecord if no VAT rate with the given ID exists.
func (m *VatModel) GetById(id int) (*Vat, error) {
	ctx := context.Background()
	stmt := `SELECT vat_id, rate
			FROM vat
			WHERE vat_id = $1`
	row := m.DB.QueryRow(ctx, stmt, id)

	var vat Vat
	err := row.Scan(&vat.Id, &vat.Rate)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, database.ErrNoRecord
		} else {
			return nil, err
		}
	}

	return &vat, nil
}
