package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"github.com/av-huette/avh-booking-system/internal/database"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Vat represents a Value Added Tax (VAT) or sales tax rate in the booking system.
// VAT rates are applied to products to calculate the tax component of prices.
// The rate is represented as a percentage (e.g., 19 = 19%)
type Vat struct {
	Id   int `json:"id" db:"vat_id"`
	Rate int `json:"rate" db:"rate"`
}

// VatModel provides database operations for Vat entities.
type VatModel struct {
	DB *database.DB
}

// CreateVat creates a new Vat with the provided rate.
// The Id is auto-generated by the database on insert.
func CreateVat(rate int) Vat {
	return Vat{
		Rate: rate,
	}
}

// Get retrieves VATs based on the provided query specification.
// It executes the SQL statement generated by the query and returns all matching VATs.
// Returns an error if the query execution fails or if row collection encounters an issue.
func (m *VatModel) Get(query *Query) ([]Vat, error) {
	ctx := context.Background()
	stmt := buildSelectSQL(query)
	rows, err := m.DB.Query(ctx, stmt)

	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) {
			fmt.Println(pgErr.Message)
			fmt.Println(pgErr.Code)
		}
	}

	vats, err := pgx.CollectRows(rows, pgx.RowToStructByName[Vat])
	if err != nil {
		fmt.Printf("CollectRows error: %v", err)
		return nil, err
	}

	return vats, nil
}

// GetById retrieves a VAT rate by its ID.
// Returns a pointer to the Vat if found, nil otherwise.
// Returns database.ErrNoRecord if no VAT rate with the given ID exists.
func (m *VatModel) GetById(id int) (*Vat, error) {
	ctx := context.Background()
	stmt := `SELECT vat_id, rate
			FROM vat
			WHERE vat_id = $1`
	row := m.DB.QueryRow(ctx, stmt, id)

	var vat Vat
	err := row.Scan(&vat.Id, &vat.Rate)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, database.ErrNoRecord
		} else {
			return nil, err
		}
	}

	return &vat, nil
}

// Insert adds a new VAT rate to the database.
// Returns the newly created VAT rate's ID and any error encountered.
func (m *VatModel) Insert(vat Vat) (int, error) {
	ctx := context.Background()
	query := `
        INSERT INTO vat (rate) 
        VALUES ($1)
        RETURNING vat_id;`
	var id int
	err := m.DB.QueryRow(ctx, query, vat.Rate).Scan(&id)

	return id, err
}
